const axios = require("axios");
const fs = require("fs-extra");
const path = require("path");

module.exports.config = {
  name: "troll",
  version: "2.0.0",
  hasPermission: 0,
  credits: "Faheem King + ChatGPT",
  description: "Roast reply with sticker and sarcastic lines",
  commandCategory: "fun",
  usages: "[text] or reply to message",
  cooldowns: 5,
};

// 🎯 Your 50 sticker IDs
const stickerIDs = [
  "1435018460122444",
  "387545538037997",
  "526220484778050",
  "526220691444696",
  "526220814778017",
  "526220978111334",
  "526221104777988",
  "526221318111300",
  "526221564777942",
  "526221711444594",
  "526221971444568",
  "374675960117310",
  "641022915913320",
  "178516915959996",
  "657500227666568",
  "608457799752028",
  "823251597693818",
  "162332943951564",
  "254593766003994",
  "237318747087785",
  "237319783754348",
  "488541014592677",
  "237318537087806",
  "369239263222822",
  "369239343222814",
  "369239383222810",
  "227877430555586",
  "1185092448213307",
  "1747080325566793",
  "745760775557020",
  "844948865605871",
  "1457681157823888",
  "1912345272349581",
  "2365626456999023",
  "1601593979955781",
  "1168273419940661",
  "1105284172903094",
  "1441692469451728",
  "767334806707657",
  "2116785328394055",
  "275366813486787",
  "1260684310693296",
  "3111681028923035",
  "1887907724764515",
  "1300887970003250",
  "2159832974066983",
  "1307792935968387",
  "294869861180504",
  "1839083466417749",
  "1839035796423833",
];

// 🧠 Troll replies list (truncated here for brevity)
const trollReplies = [
  "Tera logic sunke Windows bhi hang ho gaya.",
  "Tu bolta hai aur duniya mute ho jati hai.",
  "Tum pe pity bhi waste hai.",
  "Tera brain RAM se kam aur virus se zyada bhara hai.",
  "Tu drama itna karta hai, Star Plus bhi reject kar de.",
  "Tujhe dekh ke traffic bhi reverse gear mein chala jata hai.",
  "Tu Google pe bhi search kar, 'main kaun hoon?'",
  "Tu itna boring hai ki alarm bhi tujhe snooze kar de.",
  "Tu woh update hai jo hamesha fail ho jata hai.",
  "Tujhse milke autocorrect bhi confuse ho gaya.",
  "Tumhara swag 2G ka speed hai.",
  "Tu zindagi ka buffering moment hai.",
  "Tu warning label ke sath aana chahiye.",
  "Teri soch plastic se bhi zyada fake hai.",
  "Tera sense of humor 404 not found hai.",
  "Tu woh meme hai jo kabhi viral nahi hota.",
  "Tum toh Google Form ke required field ho, bina matlab ke.",
  "Tum wo lag ho jo game kharab kar de.",
  "Tumhare jokes sun ke calculator bhi hang ho jaye.",
  "Tu woh confusion hai jo mute mein bhi irritate karta hai.",
  "Tu itna slow hai ki snail bhi tujhe race mein hara de.",
  "Tujhe follow karke toh GPS bhi lost ho jaye.",
  "Tumhara brain safe mode mein chalta hai kya?",
  "Tu blocklist mein born hua tha kya?",
  "Tum pe insult bhi waste feel hoti hai.",
  "Tu apne life ka April Fool ban chuka hai.",
  "Tu reboot ke baad bhi slow hi rahega.",
  "Tu file not supported hai.",
  "Tum itne senseless ho, AI bhi ignore karta hoga.",
  "Tumhara mindset XP ka wallpaper hai – outdated aur sad.",
  "Tu audio glitch hai human form mein.",
  "Tu background noise se bhi bekar hai.",
  "Tujh mein IQ ka lite version chal raha hai.",
  "Tu black & white TV ho – outdated aur annoying.",
  "Tu khud ka vibe kill hai.",
  "Tum bejaan ho ya sirf boring?",
  "Tu voice note ho, bina kaam ka aur irritate karne wala.",
  "Tu logic ka loadshedding hai.",
  "Tu woh bug hai jo patch ke baad bhi fix nahi hota.",
  "Tu woh SMS hai jo kabhi deliver nahi hota.",
  "Tera dimaag trial version mein chal raha hai.",
  "Tu 144p video ka emotional scene hai.",
  "Tu slow motion mein fail hai.",
  "Tumhara dimaag Airplane Mode pe hai.",
  "Tu woh file hai jo open hote hi corrupt bolti hai.",
  "Tu unskippable ad ho – sabko irritate karta hai.",
  "Tujhse baat karke lagta hai zindagi backspace ho gayi.",
  "Tu logic ka graveyard hai.",
  "Tu reload maarte hi bhi load nahi hota.",
  "Tu us USB jaisa hai jo har baar wrong side insert hota hai.",
  "Tere jokes pe silence bhi awkward feel karti hai.",
  "Tum logic ke against protest ho.",
  "Tu woh download hai jo 99% pe atak jata hai.",
  "Tu screen recording pe lag hone wala insaan hai.",
  "Tum pe reply karne se acha phone charge kar lun.",
  "Tere profile ko dekh ke toh captcha bhi confuse ho jaye.",
  "Tu khud ka roast hai.",
  "Tu online ho ke bhi offline lagta hai.",
  "Tu low brightness pe chalta bulb hai.",
  "Tumhara attitude 140 characters se bhi kam ka hai.",
  "Tu pop-up ad ban chuka hai.",
  "Tum application error ho.",
  "Tu recycle bin ka permanent item hai.",
  "Tu woh update hai jo kabhi install nahi hota.",
  "Tujhse baat karke toh WiFi bhi disconnect ho jaye.",
  "Tu USB driver error hai.",
  "Tum toh cache memory ho – useless but stuck.",
  "Tu autocorrect ka nightmare hai.",
  "Tumhare jese logon ki wajah se airplane mode banaya gaya.",
  "Tu woh exam hai jisme sabne cheating ki phir bhi fail hua.",
  "Tujhe system ne restart karna chhod diya.",
  "Tu mute mein bhi annoying hai.",
  "Tu CTRL+ALT+DEL ka reason hai.",
  "Tu backward compatibility ka biggest fail hai.",
  "Tu life ka unnecessary update hai.",
  "Tum ek ad ho – skip karne ki koshish sab karte hain.",
  "Tu RAM full hone ka warning ho.",
  "Tu woh sticker hai jo kabhi open nahi hota.",
  "Tu zoom pe woh student hai jo mic unmute nahi karta.",
  "Tumhare jese dosto se toh enemies ache lagte hain.",
  "Tujhe dekh ke toh antivirus bhi uninstall ho jaye.",
  "Tu woh user hai jiske liye admin rights revoke kar dene chahiye.",
  "Tera processor abhi bhi Pentium III hai.",
  "Tujh mein toh logic install hua hi nahi tha.",
  "Tu download cancel hone ki feeling hai.",
  "Tu reply ka regret hai.",
  "Tujhse baat karke toh mobile mein bhi low storage aa gaya.",
  "Tu AI ka deleted dataset hai.",
  "Tu woh link hai jo broken hai.",
  "Tera vibe dial-up internet jaisa hai.",
  "Tu woh app hai jo kabhi update nahi hota.",
  "Tu scratch disk full wali error hai.",
  "Tu logic ka under construction board hai.",
  "Tu browser crash hone ki wajah hai.",
  "Tu loading screen ho – hope bhi nahi deta.",
  "Tu task manager ka end task option hai.",
  "Tu tech support ka nightmare hai.",
  "Tu woh plugin hai jo kabhi install nahi hota.",
  "Tu Excel error #VALUE ho.",
  "Tu background app jaisa hai – battery khatam karta hai.",
  "Tu lag ka full form hai.",
  "Tu memory leak ho.",
  "Tu woh cable hai jo connect nahi hoti.",
  "Tu self-destruct ka demo version hai.",
  "Tu 404 page hai.",
  "Tu woh captcha hai jo valid inputs pe bhi error deta hai.",
  "Tu woh ringtone hai jo sabko irritate kare.",
  "Tujhse baat karke Bluetooth devices bhi disconnect ho gaye.",
  "Tera vibe virus ka test positive aaya hai.",
  "Tere saath waqt bitana memory hogi – delete wali.",
  "Tu woh folder hai jo open karte hi crash ho jaye.",
  "Tu woh message hai jo seen hone ke baad bhi delete hota hai.",
  "Tu logic ka Ctrl+Z hai.",
  "Tu download retry ka permanent option hai.",
  "Tu logic se restricted ho.",
  "Tu woh document hai jisme sab typo ho.",
  "Tu woh song hai jisko log skip karte hain.",
  "Tu notifications ka spam hai.",
  "Tu logic se shadow banned hai.",
  "Tu khud ka lag hai.",
  "Tu slow boot device ho.",
  "Tu toh app permission ka deny button ho.",
  "Tu hai... magar hone ka faida kya?",
  "Tu woh account hai jo deactivate nahi hota.",
  "Tu pehle impress karne ki koshish kar... phir exist kar.",
  "Tu woh email hai jiska subject 'URGENT' ho, lekin spam ho.",
  "Tere jese logon ki wajah se password strong karna padta hai.",
  "Tu woh meme hai jisko koi like nahi karta.",
  "Tu voicemail jaisa boring hai.",
  "Tu logic ka glitch hai.",
  "Tu woh reel hai jisko swipe kar diya jata hai.",
  "Tu YouTube ke mid-roll ad ka gussa hai.",
  "Tu toh share it ka unwanted file hai.",
  "Tu download ka 'retry' button hai.",
  "Tu woh mistake hai jo undo nahi hoti.",
  "Tu chrome ka tab ho – unnecessary aur zyada.",
  "Tu error 403 forbidden face ho.",
  "Tu screen time warning ka reason hai.",
  "Tu mobile ki heating problem ho.",
  "Tu woh app ho jo install ke baad turant delete ho.",
  "Tu online class ka sleep mode hai.",
  "Tu zoom call ka frozen face hai.",
  "Tu woh face ho jo face ID reject kare.",
  "Tu woh idea hai jisko kisi ne appreciate nahi kiya.",
  "Tu woh story hai jisko koi nahi dekhta.",
  "Tu profile picture ke bina bio ho.",
  "Tu failed login attempt ho.",
  "Tu expired OTP ho.",
  "Tu broken link ho.",
  "Tu IQ ka airplane mode hai.",
  "Tu woh friend hai jo group mein sab ignore karte hain.",
  "Tu life ka loading circle hai.",
  "Tu woh password ho jo galat hai.",
  "Tu WhatsApp ka forwarded message ho.",
  "Tu logic ka fake ID hai.",
  "Tu gallery ka blurred photo ho.",
  "Tu profile pe lagaya hua random quote hai.",
  "Tu woh phone call hai jo sab avoid karte hain.",
  "Tu job interview ka reject mail hai.",
  "Tu IRL ka rage quit moment hai.",
  "Tu woh battery percentage hai jo trust nahi hota.",
  "Tu broken charging cable hai.",
  "Tu woh update notification hai jise sab ignore karte hain.",
];

module.exports.run = async function ({ api, event, args }) {
  const { threadID, messageID, senderID, messageReply } = event;

  const mentionID = messageReply?.senderID || senderID;
  const userInfo = await api.getUserInfo(mentionID);
  const mentionName = userInfo[mentionID]?.name || "User";

  const tag = [{ tag: mentionName, id: mentionID }];
  const trollLine =
    trollReplies[Math.floor(Math.random() * trollReplies.length)];
  const finalReply = `${mentionName}, ${trollLine}`;

  const stickerID = stickerIDs[Math.floor(Math.random() * stickerIDs.length)];
  const stickerURL = `https://stickers.fbcdn.net/stickers/${stickerID}.png`;
  const stickerPath = path.join(__dirname, "cache", `troll_sticker.png`);

  try {
    const image = (await axios.get(stickerURL, { responseType: "arraybuffer" }))
      .data;
    fs.writeFileSync(stickerPath, Buffer.from(image, "binary"));

    return api.sendMessage(
      {
        body: finalReply,
        mentions: tag,
        attachment: fs.createReadStream(stickerPath),
      },
      threadID,
      () => fs.unlinkSync(stickerPath),
      messageID
    );
  } catch (err) {
    console.error("Sticker load failed:", err.message);
    return api.sendMessage(
      {
        body: finalReply,
        mentions: tag,
      },
      threadID,
      messageID
    );
  }
};
